### PR TITLE
Add Fetch Buttons for Enhanced Data Filtering

### PR DESCRIPTION
**Pull request by garma-a**
Added Fetch Buttons:

View All: Fetches and displays all data entries.
Open Only: Fetches and displays data entries with the status "open".
Closed Only: Fetches and displays data entries with the status "closed".
Important Only: Fetches and displays data entries marked as important.
Easy: Fetches and displays data entries with the difficulty level "easy".
Normal: Fetches and displays data entries with the difficulty level "normal".
Hard: Fetches and displays data entries with the difficulty level "hard".
Updated Layout:

Buttons are organized into two rows for better visual clarity. The first row contains four buttons, and the second row contains three buttons.

Centralized data fetching logic to reduce code duplication and improve maintainability.
Enhanced error handling to provide better feedback to users in case of data fetch failures.
Implementation Details:

The fetchData function has been updated to handle different endpoints and parameters dynamically.
Buttons are styled to maintain consistency with the dark theme and provide a professional look.
Added appropriate spacing and layout adjustments to ensure a seamless user experience.

### CODE REVIEW

**Review by DevAbdoTolba — CHANGES_REQUESTED** [review]
image
❗❗

Test with thid mock data 
> do not upload while committing

```js
[
    {
        "id": "669d3cddda1738d017ba16e3",
        "age": "2004-05-15",
        "important": false,
        "level": "normal",
        "msg": "Hello world!",
        "name": "John Doe",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16e4",
        "age": "2004-11-03",
        "important": false,
        "level": "hard",
        "msg": "Nice to meet you.",
        "name": "Alice Smith",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16e5",
        "age": "2004-07-15",
        "important": false,
        "level": "easy",
        "msg": "How does this work?",
        "name": "Carlos Rodriguez",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16e6",
        "age": "2004-04-22",
        "important": false,
        "level": "hard",
        "msg": "Ready to start the project.",
        "name": "Emma Chen",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16e7",
        "age": "2004-09-30",
        "important": false,
        "level": "normal",
        "msg": "Looking forward to learning.",
        "name": "Ahmed Hassan",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16e8",
        "age": "2004-02-10",
        "important": false,
        "level": "normal",
        "msg": "Just a regular message.",
        "name": "Maria Garcia",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16e9",
        "age": "2004-12-28",
        "important": false,
        "level": "hard",
        "msg": "This is crucial information.",
        "name": "Yuki Tanaka",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16ea",
        "age": "2004-05-15",
        "important": false,
        "level": "normal",
        "msg": "Hello world!",
        "name": "John Doe",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16eb",
        "age": "2004-11-03",
        "important": false,
        "level": "hard",
        "msg": "Nice to meet you.",
        "name": "Alice Smith",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16ec",
        "age": "2004-07-15",
        "important": false,
        "level": "easy",
        "msg": "How does this work?",
        "name": "Carlos Rodriguez",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16ed",
        "age": "2004-04-22",
        "important": false,
        "level": "hard",
        "msg": "Ready to start the project.",
        "name": "Emma Chen",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16ee",
        "age": "2004-09-30",
        "important": false,
        "level": "normal",
        "msg": "Looking forward to learning.",
        "name": "Ahmed Hassan",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16ef",
        "age": "2004-02-10",
        "important": false,
        "level": "normal",
        "msg": "Just a regular message.",
        "name": "Maria Garcia",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16f0",
        "age": "2004-12-28",
        "important": false,
        "level": "hard",
        "msg": "This is crucial information.",
        "name": "Yuki Tanaka",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16f1",
        "age": "2004-08-05",
        "important": false,
        "level": "easy",
        "msg": "Hello! Is this interesting?",
        "name": "Liam OConnor",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16f2",
        "age": "2004-03-17",
        "important": false,
        "level": "hard",
        "msg": "Update: project is progressing well.",
        "name": "Zoe Williams",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16f3",
        "age": "2004-06-20",
        "important": false,
        "level": "normal",
        "msg": "Nothing particular to report.",
        "name": "Raj Patel",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16f4",
        "age": "2004-05-15",
        "important": false,
        "level": "normal",
        "msg": "Hello world!",
        "name": "John Doe",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16f5",
        "age": "2004-11-03",
        "important": false,
        "level": "hard",
        "msg": "Nice to meet you.",
        "name": "Alice Smith",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16f6",
        "age": "2004-07-15",
        "important": false,
        "level": "easy",
        "msg": "How does this work?",
        "name": "Carlos Rodriguez",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16f7",
        "age": "2004-04-22",
        "important": false,
        "level": "hard",
        "msg": "Ready to start the project.",
        "name": "Emma Chen",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16f8",
        "age": "2004-09-30",
        "important": false,
        "level": "normal",
        "msg": "Looking forward to learning.",
        "name": "Ahmed Hassan",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16f9",
        "age": "2004-02-10",
        "important": false,
        "level": "normal",
        "msg": "Just a regular message.",
        "name": "Maria Garcia",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16fa",
        "age": "2004-12-28",
        "important": false,
        "level": "hard",
        "msg": "This is crucial information.",
        "name": "Yuki Tanaka",
        "status": "open"
    },
    {
        "id": "669d3cddda1738d017ba16fb",
        "age": "2004-08-05",
        "important": false,
        "level": "easy",
        "msg": "Hello! Is this interesting?",
        "name": "Liam OConnor",
        "status": "open"
    }
]
```

**Comment by garma-a** [comment]
sorry for this bad styling can you test it now ?

**Review by DevAbdoTolba — CHANGES_REQUESTED** [review]
All white please,

**Review by DevAbdoTolba — APPROVED** [review]
LGTM 👍

**Pull request merged**
